on: [push, workflow_dispatch]


jobs:
  custom-collector-action:
    runs-on: ubuntu-latest
    name: A job to build a custom OpenTelemetry Collector
    steps:
      - uses: actions/checkout@v3
      - name: Build custom collector
        id: custom-collector
        uses: pbronneberg/collector-builder-action@main
        with:
          manifest-file: "test/otelcol-builder.yaml"
          architecture: "amd64"
          os: "linux"
      - name: Get the output file
        run: echo "The file is ${{ steps.custom-collector.outputs.collector-file }}"
